services:
  api:
    build: ./api
    container_name: data-center-api
    ports:
      - "8002:8002"
    depends_on:
      - database
    networks:
      - network
    
    develop:
      # create a `watch` configuration to update the api
      watch:
      - action: sync
        path: .
        target: /api
        ignore:
          - .venv/

      - action: rebuild
        path: ./uv.lock

  database:
    image: postgres:latest
    container_name: data-center-database
    ports:
      - "5433:5433"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./api/.env.production
    networks:
      - network
    
volumes:
  postgres_db:
    driver: local

networks:
  network:
    driver: bridge
    