services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    
    develop:
      # create a `watch` configuration to update the app
      watch:
      - action: sync
        path: .
        target: /app
        ignore:
          - .venv/

      - action: rebuild
        path: ./uv.lock
    